-- Stock scanner history
create table if not exists public.scan_runs (
  id bigint generated by default as identity primary key,
  scanner text not null,
  market text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  rows_written integer default 0,
  error_message text
);

create table if not exists public.scan_results (
  id bigint generated by default as identity primary key,
  scan_run_id bigint references public.scan_runs(id) on delete set null,
  scan_time timestamptz not null default now(),
  scanner text not null,
  market text,
  scan_name text,
  ticker text not null,
  company text,
  price numeric,
  change_pct numeric,
  volume numeric,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists scan_results_time_idx on public.scan_results(scan_time desc);
create index if not exists scan_results_ticker_idx on public.scan_results(ticker);
create index if not exists scan_results_scanner_idx on public.scan_results(scanner);

alter table public.scan_results enable row level security;
alter table public.scan_runs enable row level security;

-- Public read-only dashboard access. Writes are made by GitHub Actions
-- with the Supabase service-role key.
create policy "public can read scan results"
on public.scan_results for select
to anon
using (true);

create policy "public can read scan runs"
on public.scan_runs for select
to anon
using (true);

create table public.hourly_hits (
  id bigint generated by default as identity not null,
  scan_run_id bigint null,
  scan_time timestamp with time zone not null default now(),
  scanner text not null,
  market text null,
  scan_name text null,
  ticker text not null,
  company text null,
  price numeric null,
  change_pct numeric null,
  volume numeric null,
  payload jsonb not null default '{}'::jsonb,
  constraint hourly_hits_pkey primary key (id),
  constraint hourly_hits_scan_run_id_fkey foreign KEY (scan_run_id) references scan_runs (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists scan_results_time_idx on public.hourly_hits using btree (scan_time desc) TABLESPACE pg_default;

create index IF not exists scan_results_ticker_idx on public.hourly_hits using btree (ticker) TABLESPACE pg_default;

create index IF not exists scan_results_scanner_idx on public.hourly_hits using btree (scanner) TABLESPACE pg_default;
